const jobsInfo = [
    {
      "title": "Software Developer",
      "description": "Develop and maintain web applications. Collaborate with the team to deliver high-quality code.",
      "category": "Software",
      "workMode": "Remote",
      "experienceLevel": "Junior",
      "employmentType": "Full-time",
      "state": "California",
      "city": "Los Angeles",
      "salaryRangeMin": 6,
      "salaryRangeMax": 9,
      "salaryType": "LPA",
      "qualifications": ["B.Tech in Computer Science"],
      "skillsRequired": ["JavaScript", "React", "Node.js", "MongoDB"],
      "applicationDeadline": "2024-12-01",
      "companyName": "Tech Solutions Inc."
    },
    {
      "title": "Data Analyst",
      "description": "Analyze large datasets and generate insights to support business decisions.",
      "category": "Data",
      "workMode": "Hybrid",
      "experienceLevel": "Mid",
      "employmentType": "Full-time",
      "state": "New York",
      "city": "New York City",
      "salaryRangeMin": 8,
      "salaryRangeMax": 10,
      "salaryType": "LPA",
      "qualifications": ["BSc in Data Science or related field"],
      "skillsRequired": ["Python", "SQL", "Tableau", "Excel"],
      "applicationDeadline": "2024-11-15",
      "companyName": "Data Insights Corp"
    },
    {
      "title": "Graphic Designer",
      "description": "Design visuals for digital and print marketing campaigns. Work closely with the marketing team.",
      "category": "Design",
      "workMode": "On-Site",
      "experienceLevel": "Mid",
      "employmentType": "Freelance",
      "state": "Texas",
      "city": "Austin",
      "salaryRangeMin": 3000,
      "salaryRangeMax": 5000,
      "salaryType": "Per Month",
      "qualifications": ["Diploma in Graphic Design or related field"],
      "skillsRequired": ["Photoshop", "Illustrator", "Figma", "InDesign"],
      "applicationDeadline": "2024-11-25",
      "companyName": "Creative Design Studio"
    },
    {
      "title": "HR Manager",
      "description": "Manage recruitment and employee relations, ensuring a positive work environment.",
      "category": "HR",
      "workMode": "On-Site",
      "experienceLevel": "Senior",
      "employmentType": "Full-time",
      "state": "Florida",
      "city": "Miami",
      "salaryRangeMin": 10,
      "salaryRangeMax": 12,
      "salaryType": "LPA",
      "qualifications": ["MBA in Human Resources"],
      "skillsRequired": ["Recruitment", "Conflict Resolution", "Employee Relations", "HRIS"],
      "applicationDeadline": "2024-10-31",
      "companyName": "HR Pros Inc."
    },
    {
      "title": "Marketing Coordinator",
      "description": "Coordinate and execute marketing campaigns across various channels.",
      "category": "Marketing",
      "workMode": "Remote",
      "experienceLevel": "Intern",
      "employmentType": "Internship",
      "state": "Washington",
      "city": "Seattle",
      "salaryRangeMin": 3,
      "salaryRangeMax": 4,
      "salaryType": "LPA",
      "qualifications": ["BA in Marketing or related field"],
      "skillsRequired": ["SEO", "Social Media", "Email Marketing", "Content Writing"],
      "applicationDeadline": "2024-12-10",
      "companyName": "Marketing Gurus LLC"
    },
    {
      "title": "HR Manager",
      "description": "Manage recruitment and employee relations, ensuring a positive work environment.",
      "category": "HR",
      "workMode": "On-Site",
      "experienceLevel": "Senior",
      "employmentType": "Full-time",
      "state": "Maharashtra",
      "city": "Mumbai",
      "salaryRangeMin": 10,
      "salaryRangeMax": 12,
      "salaryType": "LPA",
      "qualifications": ["MBA in Human Resources"],
      "skillsRequired": ["Recruitment", "Conflict Resolution", "Employee Relations", "HRIS"],
      "applicationDeadline": "2024-10-31",
      "companyName": "HR Pros Inc."
    },
    {
      "title": "Software Engineer",
      "description": "Design, develop, and maintain software applications, collaborating with cross-functional teams.",
      "category": "Software",
      "workMode": "Remote",
      "experienceLevel": "Mid",
      "employmentType": "Full-time",
      "state": "Karnataka",
      "city": "Bangalore",
      "salaryRangeMin": 8,
      "salaryRangeMax": 10,
      "salaryType": "LPA",
      "qualifications": ["Bachelor's in Computer Science"],
      "skillsRequired": ["Java", "Python", "JavaScript", "React"],
      "applicationDeadline": "2024-11-15",
      "companyName": "Tech Innovators"
    },
    {
      "title": "Data Analyst",
      "description": "Analyze and interpret complex data sets to inform business decisions and strategies.",
      "category": "Data",
      "workMode": "Hybrid",
      "experienceLevel": "Junior",
      "employmentType": "Part-time",
      "state": "Delhi",
      "city": "New Delhi",
      "salaryRangeMin": 3,
      "salaryRangeMax": 5,
      "salaryType": "LPA",
      "qualifications": ["Bachelor's in Statistics"],
      "skillsRequired": ["SQL", "Excel", "Tableau", "Data Visualization"],
      "applicationDeadline": "2024-10-25",
      "companyName": "Data Solutions Co."
    },
    {
      "title": "Graphic Designer",
      "description": "Create visual concepts using computer software to communicate ideas that inspire and captivate consumers.",
      "category": "Design",
      "workMode": "On-Site",
      "experienceLevel": "Mid",
      "employmentType": "Freelance",
      "state": "Telangana",
      "city": "Hyderabad",
      "salaryRangeMin": 5,
      "salaryRangeMax": 7,
      "salaryType": "LPA",
      "qualifications": ["Bachelor's in Graphic Design"],
      "skillsRequired": ["Adobe Creative Suite", "Illustration", "Typography", "Branding"],
      "applicationDeadline": "2024-11-05",
      "companyName": "Creative Minds"
    },
    {
      "title": "Digital Marketing Specialist",
      "description": "Develop and implement marketing strategies to increase online presence and customer engagement.",
      "category": "Marketing",
      "workMode": "Remote",
      "experienceLevel": "Senior",
      "employmentType": "Full-time",
      "state": "Tamil Nadu",
      "city": "Chennai",
      "salaryRangeMin": 7,
      "salaryRangeMax": 9,
      "salaryType": "LPA",
      "qualifications": ["Bachelor's in Marketing"],
      "skillsRequired": ["SEO", "Google Analytics", "Social Media Marketing", "Content Creation"],
      "applicationDeadline": "2024-11-20",
      "companyName": "Market Leaders"
    },
    {
      "title": "Project Manager",
      "description": "Oversee project planning, execution, and closure, ensuring that projects are completed on time and within budget.",
      "category": "Management",
      "workMode": "Hybrid",
      "experienceLevel": "Lead",
      "employmentType": "Full-time",
      "state": "Gujarat",
      "city": "Ahmedabad",
      "salaryRangeMin": 10,
      "salaryRangeMax": 12,
      "salaryType": "LPA",
      "qualifications": ["Bachelor's in Business Administration"],
      "skillsRequired": ["Project Management", "Agile", "Team Leadership", "Risk Management"],
      "applicationDeadline": "2024-10-30",
      "companyName": "Project Experts"
    },
    {
      "title": "Sales Associate",
      "description": "Engage with customers to understand their needs and provide tailored product recommendations.",
      "category": "Sales",
      "workMode": "On-Site",
      "experienceLevel": "Intern",
      "employmentType": "Part-time",
      "state": "Uttar Pradesh",
      "city": "Noida",
      "salaryRangeMin": 2,
      "salaryRangeMax": 3,
      "salaryType": "LPA",
      "qualifications": ["High School Diploma"],
      "skillsRequired": ["Customer Service", "Sales Techniques", "Communication", "Teamwork"],
      "applicationDeadline": "2024-11-10",
      "companyName": "Retail Giants"
    },
    {
      "title": "Web Developer",
      "description": "Build and maintain websites, ensuring they are user-friendly, visually appealing, and optimized for performance.",
      "category": "Software",
      "workMode": "Remote",
      "experienceLevel": "Junior",
      "employmentType": "Full-time",
      "state": "Maharashtra",
      "city": "Pune",
      "salaryRangeMin": 4,
      "salaryRangeMax": 6,
      "salaryType": "LPA",
      "qualifications": ["Bachelor's in Web Development"],
      "skillsRequired": ["HTML", "CSS", "JavaScript", "Responsive Design"],
      "applicationDeadline": "2024-11-25",
      "companyName": "Web Solutions Inc."
    },
    {
      "title": "Business Analyst",
      "description": "Analyze business processes and systems to identify opportunities for improvement.",
      "category": "Data",
      "workMode": "Hybrid",
      "experienceLevel": "Mid",
      "employmentType": "Contract",
      "state": "Madhya Pradesh",
      "city": "Indore",
      "salaryRangeMin": 6,
      "salaryRangeMax": 8,
      "salaryType": "LPA",
      "qualifications": ["Bachelor's in Business Administration"],
      "skillsRequired": ["Analytical Skills", "Problem Solving", "Communication", "Project Management"],
      "applicationDeadline": "2024-12-01",
      "companyName": "Consulting Group"
    },
    {
      "title": "Customer Support Specialist",
      "description": "Provide support to customers, addressing inquiries and resolving issues in a timely manner.",
      "category": "Sales",
      "workMode": "On-Site",
      "experienceLevel": "Junior",
      "employmentType": "Full-time",
      "state": "Karnataka",
      "city": "Bangalore",
      "salaryRangeMin": 3,
      "salaryRangeMax": 4,
      "salaryType": "LPA",
      "qualifications": ["High School Diploma"],
      "skillsRequired": ["Communication", "Problem Solving", "Teamwork", "Time Management"],
      "applicationDeadline": "2024-10-28",
      "companyName": "Support Solutions"
    },
    {
      "title": "Content Writer",
      "description": "Create engaging content for various platforms, including websites, blogs, and social media.",
      "category": "Marketing",
      "workMode": "Remote",
      "experienceLevel": "Intern",
      "employmentType": "Part-time",
      "state": "Haryana",
      "city": "Gurgaon",
      "salaryRangeMin": 2,
      "salaryRangeMax": 3,
      "salaryType": "LPA",
      "qualifications": ["Bachelor's in English Literature"],
      "skillsRequired": ["Writing", "Research", "SEO", "Creativity"],
      "applicationDeadline": "2024-11-15",
      "companyName": "Creative Content Co."
    },
    {
      "title": "Cloud Architect",
      "description": "Design and manage cloud solutions that are scalable and secure for various applications.",
      "category": "IT",
      "workMode": "Hybrid",
      "experienceLevel": "Senior",
      "employmentType": "Full-time",
      "state": "Maharashtra",
      "city": "Mumbai",
      "salaryRangeMin": 15,
      "salaryRangeMax": 20,
      "salaryType": "LPA",
      "qualifications": ["Bachelor's in Computer Science"],
      "skillsRequired": ["Cloud Computing", "AWS", "Azure", "DevOps"],
      "applicationDeadline": "2024-11-30",
      "companyName": "Tech Innovations"
    }
]
  
module.exports = {data : jobsInfo};